import {
  durations,
  fontFamilies,
  fontSizes,
  nativeFontFamilies,
  radii,
  shadcnColors,
  shadows,
  spacing,
  timerPulse,
} from './theme.ts';

export type ChannelMap = Record<string, string>;

export interface ParsedTokens {
  light: ChannelMap;
  dark: ChannelMap;
  poo: ChannelMap;
}

const CHANNELS = /^\d{1,3} \d{1,3} \d{1,3}$/;

export function parseTokenCss(css: string): ParsedTokens {
  const withoutComments = css.replace(/\/\*[\s\S]*?\*\//g, '');
  const blocks = [...withoutComments.matchAll(/([^{}]+)\{([^{}]*)\}/g)].map(([, selector, body]) => ({
    selector: selector!.trim(),
    declarations: [...body!.matchAll(/--([\w-]+)\s*:\s*([^;]+);/g)].map(
      ([, name, value]) => [name!, value!.trim()] as const,
    ),
  }));

  const colours = (selectorTest: (selector: string) => boolean) =>
    Object.fromEntries(
      blocks
        .filter((block) => selectorTest(block.selector))
        .flatMap((block) => block.declarations)
        .filter(([, value]) => CHANNELS.test(value)),
    );

  const all = colours((selector) => selector.startsWith(':root'));
  const light = colours((selector) => selector.includes('[data-theme="light"]'));
  const dark = colours((selector) => selector.includes('[data-theme="dark"]'));
  const poo = Object.fromEntries(
    Object.entries(all)
      .filter(([name]) => name.startsWith('poo-'))
      .map(([name, value]) => [name.slice('poo-'.length), value]),
  );

  const missingInDark = Object.keys(light).filter((name) => !(name in dark));
  if (missingInDark.length > 0) throw new Error(`Dark theme is missing: ${missingInDark.join(', ')}`);
  if (Object.keys(light).length === 0 || Object.keys(poo).length === 0) throw new Error('No colour tokens found');

  return { light, dark, poo };
}

export function renderWebCss(tokens: ParsedTokens): string {
  const lines = [
    '/* Generated by packages/tokens/scripts/generate.ts. Do not edit. */',
    '@custom-variant dark (&:where(.dark, .dark *, [data-theme="dark"], [data-theme="dark"] *));',
    '',
    '@theme inline {',
    ...Object.keys(tokens.light).map((name) => `  --color-${name}: rgb(var(--${name}));`),
    ...Object.keys(tokens.poo).map((name) => `  --color-poo-${name}: rgb(var(--poo-${name}));`),
    ...shadcnColors.map((name) => `  --color-${name}: var(--${name});`),
    `  --font-sans: ${fontFamilies.sans};`,
    `  --font-brand: ${fontFamilies.brand};`,
    ...Object.entries(fontSizes).flatMap(([name, style]) => [
      `  --text-${name}: ${style.fontSize};`,
      `  --text-${name}--line-height: ${style.lineHeight};`,
      ...(style.letterSpacing ? [`  --text-${name}--letter-spacing: ${style.letterSpacing};`] : []),
    ]),
    ...Object.entries(spacing).map(([name, value]) => `  --spacing-${name}: ${value};`),
    ...Object.entries(radii).map(([name, value]) => `  --radius-${name}: ${value};`),
    `  --animate-timer-pulse: babble-pulse ${timerPulse};`,
    '}',
    '',
    ...shadows.map((name) => `@utility shadow-${name} {\n  box-shadow: var(--shadow-${name});\n}`),
    ...Object.entries(durations).map(
      ([name, value]) => `@utility duration-${name} {\n  transition-duration: ${value};\n}`,
    ),
    '',
  ];
  return lines.join('\n');
}

export function renderNativePreset(tokens: ParsedTokens): string {
  const colours: Record<string, unknown> = Object.fromEntries(
    Object.keys(tokens.light).map((name) => [name, `rgb(var(--${name}) / <alpha-value>)`]),
  );
  colours.poo = Object.fromEntries(
    Object.keys(tokens.poo).map((name) => [name, `rgb(var(--poo-${name}) / <alpha-value>)`]),
  );

  const preset = {
    darkMode: 'class',
    theme: {
      extend: {
        colors: colours,
        fontFamily: nativeFontFamilies,
        fontSize: Object.fromEntries(
          Object.entries(fontSizes).map(([name, { fontSize, ...rest }]) => [name, [fontSize, rest]]),
        ),
        spacing,
        minHeight: { tap: spacing.tap, 'tap-lg': spacing['tap-lg'] },
        minWidth: { tap: spacing.tap },
        borderRadius: radii,
        transitionDuration: durations,
      },
    },
  };

  return [
    '// Generated by packages/tokens/scripts/generate.ts. Do not edit.',
    `module.exports = ${JSON.stringify(preset, null, 2)};`,
    '',
  ].join('\n');
}

export function renderVarsModule(tokens: ParsedTokens): string {
  const prefix = (map: ChannelMap, namePrefix = '') =>
    Object.fromEntries(Object.entries(map).map(([name, value]) => [`--${namePrefix}${name}`, value]));

  return [
    '// Generated by packages/tokens/scripts/generate.ts. Do not edit.',
    `export const lightVars = ${JSON.stringify({ ...prefix(tokens.light), ...prefix(tokens.poo, 'poo-') }, null, 2)} as const;`,
    '',
    `export const darkVars = ${JSON.stringify({ ...prefix(tokens.dark), ...prefix(tokens.poo, 'poo-') }, null, 2)} as const;`,
    '',
    'export type TokenVar = keyof typeof lightVars;',
    '',
  ].join('\n');
}
