/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as JoinCodeRouteImport } from './routes/join/$code'
import { Route as OnboardingBabyRouteImport } from './routes/onboarding/baby'
import { Route as OnboardingDayStartRouteImport } from './routes/onboarding/day-start'
import { Route as OnboardingFamilyRouteImport } from './routes/onboarding/family'
import { Route as OnboardingInviteRouteImport } from './routes/onboarding/invite'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBabyRoute = OnboardingBabyRouteImport.update({
  id: '/baby',
  path: '/baby',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingDayStartRoute = OnboardingDayStartRouteImport.update({
  id: '/day-start',
  path: '/day-start',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingFamilyRoute = OnboardingFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingInviteRoute = OnboardingInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => OnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/history': typeof AppHistoryRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$code': typeof JoinCodeRoute
  '/onboarding/baby': typeof OnboardingBabyRoute
  '/onboarding/day-start': typeof OnboardingDayStartRoute
  '/onboarding/family': typeof OnboardingFamilyRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/history': typeof AppHistoryRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$code': typeof JoinCodeRoute
  '/onboarding/baby': typeof OnboardingBabyRoute
  '/onboarding/day-start': typeof OnboardingDayStartRoute
  '/onboarding/family': typeof OnboardingFamilyRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stats': typeof AppStatsRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$code': typeof JoinCodeRoute
  '/onboarding/baby': typeof OnboardingBabyRoute
  '/onboarding/day-start': typeof OnboardingDayStartRoute
  '/onboarding/family': typeof OnboardingFamilyRoute
  '/onboarding/invite': typeof OnboardingInviteRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/history'
    | '/settings'
    | '/stats'
    | '/api/health'
    | '/auth/callback'
    | '/join/$code'
    | '/onboarding/baby'
    | '/onboarding/day-start'
    | '/onboarding/family'
    | '/onboarding/invite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/sign-in'
    | '/history'
    | '/settings'
    | '/stats'
    | '/api/health'
    | '/auth/callback'
    | '/join/$code'
    | '/onboarding/baby'
    | '/onboarding/day-start'
    | '/onboarding/family'
    | '/onboarding/invite'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/onboarding'
    | '/sign-in'
    | '/_app/history'
    | '/_app/settings'
    | '/_app/stats'
    | '/api/health'
    | '/auth/callback'
    | '/join/$code'
    | '/onboarding/baby'
    | '/onboarding/day-start'
    | '/onboarding/family'
    | '/onboarding/invite'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  JoinCodeRoute: typeof JoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/baby': {
      id: '/onboarding/baby'
      path: '/baby'
      fullPath: '/onboarding/baby'
      preLoaderRoute: typeof OnboardingBabyRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/day-start': {
      id: '/onboarding/day-start'
      path: '/day-start'
      fullPath: '/onboarding/day-start'
      preLoaderRoute: typeof OnboardingDayStartRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/family': {
      id: '/onboarding/family'
      path: '/family'
      fullPath: '/onboarding/family'
      preLoaderRoute: typeof OnboardingFamilyRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/invite': {
      id: '/onboarding/invite'
      path: '/invite'
      fullPath: '/onboarding/invite'
      preLoaderRoute: typeof OnboardingInviteRouteImport
      parentRoute: typeof OnboardingRoute
    }
  }
}

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatsRoute: AppStatsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingBabyRoute: typeof OnboardingBabyRoute
  OnboardingDayStartRoute: typeof OnboardingDayStartRoute
  OnboardingFamilyRoute: typeof OnboardingFamilyRoute
  OnboardingInviteRoute: typeof OnboardingInviteRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingBabyRoute: OnboardingBabyRoute,
  OnboardingDayStartRoute: OnboardingDayStartRoute,
  OnboardingFamilyRoute: OnboardingFamilyRoute,
  OnboardingInviteRoute: OnboardingInviteRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  JoinCodeRoute: JoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
